# Generated by Django 4.2.6 on 2023-10-12 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_alter_lesson_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('name',), 'verbose_name': 'курс', 'verbose_name_plural': 'курсы'},
        ),
    ]
